# ==========================
# Default Training Config
# ==========================

training:
  version: v1   # v1, v2, v3
  batch_size: 8
  epochs: 50
  epoch_start: 0
  learning_rate: 0.001

  # v1/v2 specific (arg_parser.py)
  dense_blocks: 3
  dense_units: 4
  lambda_adv: 0.01
  lambda_grad_pen: 10  # 
  lambda_cyc: 0.01
  lambda_idt: 0.005
  crit_iter: 3
  train_only: ""        # '', GENERATORS, DISCRIMINATORS
  model: "3DRDN"        # 3DRDN, 3DRDN-WGAN

  # v3 specific (arg_parser2.py)
  num_rdb_blocks: 8
  growth_rate: 16
  num_dense_layers: 4
  lr_g: 1e-4
  lr_d: 1e-4
  residual_scaling: 0.2

model:
  version: v3   # v1, v2, v3
  num_blocks: 16
  num_layers: 8